package dev.rulsoft.nb22.domain.numero.model

data class Numero (
    val id: Int,
    val alias: String,
    val resumen: String,
    val resumenFree: String,
    val frase: String,
    val finalidad: String,
    val nombre: String,
    val dia: String,
    val mesEquilibrio: String,
    val mesDesequilibrio: String,
    val anyo: String,
    val ppEquilibrio: String,
    val ppDesequilibrio: String,
    val pd: String,
    val ne: String,
    val ci: String,
    val ce: String,
    val cp: String,
    val cg: String,
    val ps: String,
    val pa: String,
    val be: String,
    val de: String,
    val pf: String,
    val rne: String,
    val rci: String,
    val rce: String,
    val rcp: String,
    val rup: String,
    val rua: String
)
